services:
    php:
        # Old version
        # image: ${IMAGES_PREFIX:-}app-php
        image: prevedka/smart-bot-php
        container_name: bot-app
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
            TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
            # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
            # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
            MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
            MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
            MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            # The two next lines can be removed after initial installation
            SYMFONY_VERSION: ${SYMFONY_VERSION:-}
            STABILITY: ${STABILITY:-stable}
            MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=false
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./frankenphp/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
        ports:
            # HTTP
            -   target: 80
                published: ${HTTP_PORT:-80}
                protocol: tcp
            # HTTPS
            -   target: 443
                published: ${HTTPS_PORT:-443}
                protocol: tcp
            # HTTP/3
            -   target: 443
                published: ${HTTP3_PORT:-443}
                protocol: udp
        networks:
            - bot

    db:
        image: mysql:latest
        container_name: bot-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: bot
            MYSQ_TEST_DATABASE: bot_test
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        volumes:
            - ./frankenphp/database/init.sql:/usr/local/bin/init.sql
        command: mysqld --init-file="/usr/local/bin/init.sql"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root_password --execute 'SHOW DATABASES'"
            timeout: 10s
            interval: 10s
        ports:
            - "3306:3306"
        networks:
            - bot

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
#    postgresdata:
    caddy_data:
    caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

networks:
    bot:
