services:
    App\Shared\Application\Clock:
        class: App\Tests\Mock\MockClock

    App\Shared\Application\UuidProvider:
        class: App\Tests\Mock\MockUuidProvider

    App\Shared\Domain\TelegramInterface:
        class: App\Tests\Mock\MockTelegram
