<?php

declare(strict_types=1);

namespace App\User\Domain;

enum UserStateEnum: string
{
    case IDLE = 'IDLE';
    case RECEIVING_NAME_FOR_CREATING = 'RECEIVING_NAME_FOR_CREATING';
    case RECEIVING_DESCRIPTION_FOR_CREATION = 'RECEIVING_DESCRIPTION_FOR_CREATION';
    case RECEIVING_MAX_PARTICIPANTS_COUNT_FOR_CREATION = 'RECEIVING_MAX_PARTICIPANTS_COUNT_FOR_CREATION';
    case RECEIVING_MIN_PARTICIPANTS_COUNT_FOR_CREATION = 'RECEIVING_MIN_PARTICIPANTS_COUNT_FOR_CREATION';
    case RECEIVING_DATE_FOR_CREATION = 'RECEIVING_DATE_FOR_CREATION';

    case RECEIVING_NAME_FOR_EDITING = 'RECEIVING_NAME_FOR_EDITING';
    case RECEIVING_DESCRIPTION_FOR_EDITING = 'RECEIVING_DESCRIPTION_FOR_EDITING';
    case RECEIVING_MIN_PARTICIPANTS_COUNT_FOR_EDITING = 'RECEIVING_MIN_PARTICIPANTS_COUNT_FOR_EDITING';
    case RECEIVING_MAX_PARTICIPANTS_COUNT_FOR_EDITING = 'RECEIVING_MAX_PARTICIPANTS_COUNT_FOR_EDITING';
    case RECEIVING_DATE_FOR_EDITING = 'RECEIVING_DATE_FOR_EDITING';

    case RECEIVING_PARTICIPANT = 'RECEIVING_PARTICIPANT';
    case RECEIVING_MESSAGE_FOR_EVERYONE = 'RECEIVING_MESSAGE_FOR_EVERYONE';

    case RECEIVING_MESSAGE_FOR_PARTICIPANTS = 'RECEIVING_MESSAGE_FOR_PARTICIPANTS';

    case RECEIVING_CONFIRMATION_CLUB_CANCELLATION = 'RECEIVING_CONFIRMATION_CLUB_CANCELLATION';

    case RECEIVING_SPEAKING_CLUB_FEEDBACK = 'RECEIVING_SPEAKING_CLUB_FEEDBACK';

    case RECEIVING_ADD_BAN = 'RECEIVING_ADD_BAN';
    case RECEIVING_ADD_WARNING = 'RECEIVING_ADD_WARNING';

    /**
     * @return array<string, string>
     */
    public static function getAsArray(): array
    {
        return array_reduce(
            self::cases(),
            static fn (array $choices, UserStateEnum $type) => $choices + [
                $type->name => $type->value,
            ],
            [],
        );
    }
}
