name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: prevedka/smart-bot-php
        with:
          pull: true
          load: true
          files: |
            docker-compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Copy .env.locals
        run: cp .env.local.example .env.local && cp .env.test.local.example .env.test.local
      -
        name: Copy phpunit.xml
        run: cp phpunit.xml.dist phpunit.xml
      -
        name: Start services
        run: docker compose up -d --no-build
      -
        name: Waiting for containers to start
        run: sleep 10
      -
        name: Run PHPUnit
        run: docker compose exec -T php bin/phpunit -c phpunit.xml
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
